export enum ActionType {
  GET_WEATHER_BY_CITY_REQUESTED = 'GET_WEATHER_BY_CITY_REQUESTED',
  GET_WEATHER_BY_CITY_LOADED = 'GET_WEATHER_BY_CITY_LOADED',
  GET_DAILY_FORECAST_BY_CITY_REQUESTED = 'GET_DAILY_FORECAST_BY_CITY_REQUESTED',
  GET_DAILY_FORECAST_BY_CITY_LOADED = 'GET_DAILY_FORECAST_BY_CITY_LOADED',
  CLEAR_WEATHER_AND_FORECAST_DATA = 'CLEAR_WEATHER_AND_FORECAST_DATA',
}
